# Generated by Django 2.0.5 on 2021-02-13 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coupon',
            options={'verbose_name': 'coupon', 'verbose_name_plural': 'coupons'},
        ),
    ]
